apiVersion: v1
kind: Namespace
metadata:
  name: preinterview-test
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preinterview-deploy
  namespace: preinterview-test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: preinterview
  template:
    metadata:
      labels:
        app: preinterview
    spec:
      containers:
      - name: preinterview-demo
        image: amyjdocker/sinatrademo:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 256m
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: preinterview
  name: preinterview-service
  namespace: preinterview-test
spec:
  type: LoadBalancer  # use LoadBalancer as type here
  ports:
    - port: 3000
  selector:
    app: preinterview